### ISSUE TITLE
About Baseline Bugs

### ISSUE THREAD

**Issue by wanghr-git** [AICyberTeam/DFC2023-baseline#1]
In the dataset.py of track2, I see ‘dsmnpy’ folder and 'npy' file is loaded in the code after, I don't know where is the 'npy' file or how to generate it?
<img width="479" alt="image" src="https://user-images.githubusercontent.com/63220803/210920484-a348b43f-09a6-4dce-9436-d2de77876fb0.png">

**Comment by WingkeungM** [comment]
.npy file is another format of height data, contestants can use .tif file directly.
