### ISSUE TITLE
The baseline does not read the sar file

### ISSUE THREAD

**Issue by Rowan-L** [AICyberTeam/DFC2023-baseline#7]
Sorry, I didn't find the code to read the sar file in the baseline, and the input to Res_Deeplab is a 3 channel image, so where is the sar file loaded?

**Comment by Rowan-L** [comment]
In track2

**Comment by WingkeungM** [comment]
The reading of the SAR file is given in the code of track1, and the contestants can check and modify the corresponding code by themselves.
